### ISSUE TITLE
Case sensitiveness in URLs

### ISSUE THREAD

**Issue by Adrianzo** [Bioconductor/bioconductor.org#1]
Bioconductor.org is the only website I know that has case-sensitive URLs.

For example:

[this link](http://bioconductor.org/packages/release/bioc/html/Biobase.html) works, because it has the capital B for naming the html file.

[this one](http://bioconductor.org/packages/release/bioc/html/biobase.html) doesn't (as in page not found, custom 404 message).

**Comment by mtmorgan** [comment]
It's only URLs in the packages/ path, probably because of the rewrite rules https://github.com/Bioconductor/bioconductor.org/blob/master/assets/packages/.htaccess .

**Comment by hpages** [comment]
@Adrianzo Whoa, really? Maybe you don't know a lot of websites:
work: https://en.wikipedia.org/wiki/Bioconductor
do not work: https://en.wikipedia.org/wiki/BioconductoR
work: https://genome.ucsc.edu/FAQ/FAQreleases.html
do not work: https://genome.ucsc.edu/FAQ/FAQreleaseS.html
etc...

**Comment by hpages** [comment]
@mtmorgan and we should keep it that way because package names ARE case sensitive!
