### ISSUE TITLE
Landing page links to other BioC packages don't work

### ISSUE THREAD

**Issue by LTLA** [Bioconductor/bioconductor.org#11]
For example, if I go to the [simpleSingleCell](http://bioconductor.org/packages/devel/workflows/html/simpleSingleCell.html) landing page, and I click on any of the Bioconductor packages in `Depends`, I get directed to the address http://bioconductor.org/packages/bioc/html/XXX.html where XXX is the package name. This doesn't go anywhere, just ending up in a "Page Not Found" error page.

**Comment by lshep** [comment]
Thanks for bring this to our attention.  We will look into the underlying redirects.

**Comment by vobencha** [comment]
I don't think this is related to redirects but is instead the the auto-generated paths in the workflow landing pages (release and devel). The paths specify a prefix 3 levels up but we only want to go 2. These levels are defined by the file structure on master.bioconductor.org.

For example in biocadmin@ip-172-30-0-180:/loc/www/bioconductor-test.fhcrc.org/packages/3.8/workflows/html/simpleSingleCell.html we have this:
```
<a href="../../../bioc/html/limma.html">limma</a>
```
But we want this:
```
<a href="../../bioc/html/limma.html">limma</a>
```
These pages are generated on staging so the code to modify is probably in https://github.com/Bioconductor/bioconductor.org. Or maybe it's a stand-alone script on staging ... @lshep would know better than me.

**Comment by lshep** [comment]
It seems like it is only an issue with the links on the workflow landing pages.  I will look into this when I get back on monday.  I found where the issue is but want to make sure I do the fix right and test it locally before pushing it up.
