### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by vjcitn** [Bioconductor/bioconductor.org#114]
https://bioconductor.org/developers/package-submission/#annPackage

includes broken link 
at

Annotation Packages
Annotation packages contain lightly or non-curated data from a public source and are updated with each Bioconductor release (every 6 months). They are a source of general annotation for one or many organisms and are not specific to a particular experiment. When possible, they should support the select() interface from AnnotationDbi.

Annotation packages should NOT be posted to the tracker repository. Instead send an email to packages@bioconductor.org with a description of the proposed annotation package and futher instructions of where to send the package will be provided. Whenever possible Annotation Packages should use the AnnotationHub for managing files.

the reference to AnnotationHub in last line is the broken

https://bioconductor.org/packages/devel/bioc/vignettes/AnnotationHub/inst/doc/CreateAnAnnotationPackage.html

**Comment by vjcitn** [comment]
Same for ExperimentHub reference in prior section

**Comment by lshep** [comment]
Thanks! Yes we switched the create a package vignette to HubPub.  I'll work on the update.

**Comment by lshep** [comment]
http://www.bioconductor.org/packages/devel/bioc/vignettes/HubPub/inst/doc/CreateAHubPackage.html
