### ISSUE TITLE
package naming policy should include following code of conduct

### ISSUE THREAD

**Issue by LiNk-NY** [Bioconductor/bioconductor.org#143]
Hi Lori, @lshep 

Related to previous packages that required a new name, we should have some information 
regarding packages that do not follow this naming policy listed or linked somewhere on this page: 

https://bioconductor.org/developers/package-submission/#naming

as linked in the Bioconductor issue tracker initial comment.

**Comment by lshep** [comment]
All of these pages will be going away and redirecting to the pages on contributions.bioconductor.org. 

http://contributions.bioconductor.org/package-name.html

Please open an issue there if you feel like the information on that page is incomplete
