### ISSUE TITLE
Bioc devel landing pages: NEWS missing

### ISSUE THREAD

**Issue by HenrikBengtsson** [Bioconductor/bioconductor.org#152]
It looks like NEWS files are missing on Bioc devel landing pages, e.g. missing on <https://www.bioconductor.org/packages/devel/bioc/html/Biobase.html>, but  there on <https://www.bioconductor.org/packages/release/bioc/html/Biobase.html>.

**Comment by lshep** [comment]
@jwokaty  / @hpages  It looks like the VIEWS file for devel/3.16 have `hasNEWS: FALSE` for all packages which is causing this?  

https://www.bioconductor.org/packages/devel/bioc/VIEWS

**Comment by jwokaty** [comment]
I'll look into this.

**Comment by jwokaty** [comment]
This has been resolved with the most recent propagation.
