### ISSUE TITLE
FAQ mentions BiocLite

### ISSUE THREAD

**Issue by llrs** [Bioconductor/bioconductor.org#16]
[FAQ](https://github.com/Bioconductor/bioconductor.org/blob/a26171ce8539865b8509be74984a2783e4244dfc/content/help/faq.md) still mentions BiocLite. Shouldn't it be updated?

**Comment by LiNk-NY** [comment]
Hi Lluís, @llrs 
Thanks for pointing this out. I'll work on it. 

-Marcel

**Comment by LiNk-NY** [comment]
See PR #17

**Comment by llrs** [comment]
Great work!
Sorry to mix a bit but there are other pull requests pending I don't know if you could review them too

**Comment by lshep** [comment]
I'll try and look at the other pull requests sometime this week.  sorry for the delay
