### ISSUE TITLE
Is there a packages.rds file like CRAN's https://cran.r-project.org/web/packages/packages.rds

### ISSUE THREAD

**Issue by urisohn** [Bioconductor/bioconductor.org#162]
I maintain `groundhog`, a package that brings version control to R package handling. I am about to launch v2.0.0 which will add github and gitlab packages, but it still does not work with bioconductor packages. I plan on adding this capabiliy on the next major release. To do so it would be useful to have a database with all packages and their dependencies on each version on bioconductor. Something like https://cran.r-project.org/web/packages/packages.rds does such a file exist?  I guess it is possible to scrape this information from the site, but seems much better to simply download the file if it exist.  Thanks,

Uri

http://groundhogr.com

**Comment by lshep** [comment]
We have a VIEWS file that is similar but not exact: 
https://www.bioconductor.org/packages/devel/bioc/VIEWS

That exists for release/devel  or numeric version: 
https://www.bioconductor.org/packages/3.13/bioc/VIEWS

**Comment by urisohn** [comment]
Perfect, thank you.

**Comment by lshep** [comment]
Please by advised that there is a VIEWS for each type of Bioconductor package. Those were for software but there is also: 
Experiment Data: https://www.bioconductor.org/packages/devel/data/experiment/VIEWS
Annotation: https://www.bioconductor.org/packages/devel/data/annotation/VIEWS
Workflows: https://www.bioconductor.org/packages/devel/workflows/VIEWS
