### ISSUE TITLE
Add Mac arm64 binaries to package landing pages

### ISSUE THREAD

**Issue by hpages** [Bioconductor/bioconductor.org#175]
@lshep @jwokaty 

With the Mac arm64 binaries now available in BioC 3.16, we need to discuss the impact on package landing pages.

The good news is that it looks like Jen already made the necessary adjustments in `biocViews::genReposControlFiles()` to list those binaries in the `VIEWS` file. See the `mac.binary.big-sur-arm64.ver` lines in https://bioconductor.org/packages/3.16/bioc/VIEWS :+1: 

So the scripts on staging would need to be modified to put the link to those binaries on the package landing pages. See for example https://bioconductor.org/packages/3.16/Biobase. The various types of packages are listed at the bottom of the page. The new binaries could be labelled as "macOS binary (arm64)" for consistency with what the CRAN folks do on their own package landing pages (see for example https://cran.r-project.org/package=car). Also note that, right now, we label the Mac Intel binaries as "macOS 10.13 (High Sierra)" but we should probably re-label them as "macOS binary (x86_64)" for consistency with CRAN.

One remaining caveat is what happens to the "build" badge. I don't know the details but I suspect that the script on staging consults the [`BUILD_STATUS_DB.txt`](https://bioconductor.org/checkResults/3.16/bioc-LATEST/BUILD_STATUS_DB.txt) file to infer the overall "build" status of a package. Problem is that the arm64 builds are their own separate builds at the moment (i.e. they're not part of the daily builds), with their own schedule (they run twice a week only). This might change in the future when we have enough Mac arm64 computing power to keep up with the pace of the daily builds. In the meantime, this means that the build status for kjohnson is not included in the `BUILD_STATUS_DB.txt` file produced by the daily builds. Instead it's in its own `BUILD_STATUS_DB.txt` file here: https://bioconductor.org/checkResults/3.16/bioc-mac-arm64-LATEST/BUILD_STATUS_DB.txt Of course there are ways to handle this but...

The easy solution is to not do anything about it and live with the fact that an arm64 failure won't have any effect on the "build" badge :wink:. Note that, even if we were able to generate the correct "build" badge (i.e. a badge that also considers arm64 build status), clicking on the badge would still take you to the daily build report where the results for arm64 are not displayed. It would be very confusing to display a red "build" badge on the package landing page, because of an arm64 failure, and to end up on a build report where everything is green!

So probably not a big deal to ignore the arm64 build status for the "build" badge for now. It's a temporary situation anyways.

Let me guys know how I can help.

Thanks,
H.

**Comment by lshep** [comment]
cool.  doing other release related tasks today but probably could start looking at landing page updates tomorrow

**Comment by lshep** [comment]
@hpages  / @jwokaty   just pushed up the change that will allow the M1 on the landing page.  

As far as the badge; Yes quite complicated to include this information.  I'm okay with ignoring this as part of the build badge for now if everyone else is.

**Comment by hpages** [comment]
Looks great: [https://bioconductor.org/packages/3.16/Biobase](https://bioconductor.org/packages/3.16/Biobase)

Also nice to have the macOS binary explicitly marked as for x86_64 in release: [https://bioconductor.org/packages/3.15/Biobase](https://bioconductor.org/packages/3.15/Biobase)

Thanks Lori!
