### ISSUE TITLE
Building package landing pages locally

### ISSUE THREAD

**Issue by grimbough** [Bioconductor/bioconductor.org#184]
Is it possible to build the package landing pages locally?  

I've read the instructions at https://github.com/Bioconductor/bioconductor.org#step-1-rake-get_json but I get stuck on step 1 where there is no `get_json.sh` script in the repository.

Ideally I'd do this with the Docker image, which works great for testing the rest of the site content, but I'll take any mechanism.

The reason I'm asking is that I'd like to try adding the code browser links to the landing page e.g. https://code.bioconductor.org/browse/BiocStyle to increase the visibility of the service.  However I don't think I'll get very far without some local testing of the code.

Of course, if we don't think it's a good idea to have those links then I'll stop trying!

**Comment by lshep** [comment]
Yes I do it all the time.  I actually have to set this up on a new computer so perhaps I can refine the documentation a bit more. 

Does just  `rake get_json`  work? 

Really the get.json.sh  was a helper to run the rake commands

**Comment by lshep** [comment]
We talked about adding the code.bioconductor.org  -- if you proceed with this remember that the landing pages are generated for all types of packages --  so you'll need to make sure whatever change you make doesn't break say the data-experiment or workflow landing pages since code.bioconductor.org  only has the software packages

**Comment by grimbough** [comment]
> Yes I do it all the time. I actually have to set this up on a new computer so perhaps I can refine the documentation a bit more.
> 
> Does just `rake get_json` work?
> 
> Really the get.json.sh was a helper to run the rake commands

Great, thanks for that.  I can even do it inside the docker container without installing anything extra.  So I've got the JSON step done.  Is it then just a case of running `nanoc` and waiting, or do I need to provide some arguments?

> We talked about adding the code.bioconductor.org -- if you proceed with this remember that the landing pages are generated for all types of packages -- so you'll need to make sure whatever change you make doesn't break say the data-experiment or workflow landing pages since code.bioconductor.org only has the software packages

Another reason I want to test it locally.  It's not immediately clear to me whats in the `@package` found in https://github.com/Bioconductor/bioconductor.org/blob/master/layouts/_bioc_views_package_detail.html but I'm hoping there's someway to make this an optional field.  Alternatively, I can look into updating the code browser with the other package types.  For that I'd probably need an estimate of the storage requirements to approach our IT department.

**Comment by lshep** [comment]
yeah if you already installed the other needed ruby gems --  see https://github.com/Bioconductor/bioconductor.org#build-the-site
