### ISSUE TITLE
update code of conduct

### ISSUE THREAD

**Issue by lshep** [Bioconductor/bioconductor.org#188]
It was requested to update the code of conduct to https://bioconductor.github.io/CodeOfConduct/CoC_doc.html  but with the current restructuring it appears to be linked to a different out-of-date page. 

https://github.com/Bioconductor/bioconductor.org/blob/master/content/about/code-of-conduct.md

How do we make this consistent and easier for updates as I'm not sure how to proceed to update the page

**Comment by lshep** [comment]
@kevinrue  @SaskiaFreytag

**Comment by kevinrue** [comment]
I'm not sure what is still pointing to https://bioconductor.github.io/CodeOfConduct/CoC_doc.html
but the code of conduct has moved to 
https://github.com/Bioconductor/bioc_coc_multilingual

- Edit https://github.com/Bioconductor/bioc_coc_multilingual/blob/main/en-US.Rmd
- Then open an issue [here](https://github.com/Bioconductor/bioc_coc_multilingual/issues/new/choose) to request a 'New version of translated documents'

Let me know if there's anything I missed
