### ISSUE TITLE
Download stats data missing

### ISSUE THREAD

**Issue by bschilder** [Bioconductor/bioconductor.org#191]
Hi there, 

I'm writing a function that pulls data on download stats for all packages in Bioc and I noticed today that the tabular-formatted data seems to be missing:
https://bioconductor.org/packages/stats/bioc/bioc_pkg_stats.tab

Though the html page is still there:
https://bioconductor.org/packages/stats/

Do you know why this might be? Did the URL change or was this just a temporary outage?

Best, 
Brian

**Comment by LiNk-NY** [comment]
Hi Brian, @bschilder 

We've been working on re-calculating the download stats and 
they may be unavailable as they are updated.
Hervé @hpages can provide an update. 

FWIW, have you looked at the functions in `BiocPkgTools`, e.g., https://github.com/seandavi/BiocPkgTools/blob/master/R/biocDownloadStats.R 
to obtain download stats? 

Best,
Marcel

**Comment by bschilder** [comment]
Ok cool, as long as it's a known thing! Thanks for the quick reply @LiNk-NY. 

I hadn't come across `BiocPkgTools` before but will definitely check it out! I've tried using [`dlstats`](https://cran.r-project.org/web/packages/dlstats/index.html) before as well, but found this was making a ton of small per-day queries (which can take some time for lots of packages) when I only need the total downloads across all time. So I'll give `BiocPkgTools` a try!

Thanks again, 
Brian
