### ISSUE TITLE
Search results not clear enough

### ISSUE THREAD

**Issue by Adrianzo** [Bioconductor/bioconductor.org#2]
Whenever someone searches for a package the results are somewhat overwhelming... the different releases could use of some visual help. Right now you see the actual URLs. IDK, maybe using badges in the results? Most users won't visually parse the actual URLs! I mean, it takes some experience to do it. At least that's what happened to me during my first months looking for search results and ending in "devel" pages, hehe.

as  an example:

```
Your search for biobase returned 11282 results.

Bioconductor - Biobase - /packages/release/bioc/html/Biobase.html
Bioconductor - Biobase
Biobase - /packages/bioc/1.6/src/contrib/html/Biobase.html
Biobase
Biobase - /packages/bioc/1.7/src/contrib/html/Biobase.html
Biobase
Biobase - /packages/2.3/bioc/html/Biobase.html
Biobase
Biobase - /packages/2.4/bioc/html/Biobase.html
Biobase
Bioconductor - Biobase (development version) - /packages/devel/bioc/html/Biobase.html
Bioconductor - Biobase (development version)
Bioconductor - Biobase - /packages/2.14/bioc/html/Biobase.html
Bioconductor - Biobase
Bioconductor - Biobase - /packages/2.11/bioc/html/Biobase.html
Bioconductor - Biobase
Bioconductor - Biobase - /packages/2.13/bioc/html/Biobase.html
Bioconductor - Biobase
Bioconductor - Biobase - /packages/2.12/bioc/html/Biobase.html
Bioconductor - Biobase
Bioconductor - Biobase - /packages/3.1/bioc/html/Biobase.html
Bioconductor - Biobase
```

Could be better be parsed by the server, instead of giving that task to the user. Like returning a sorted list of unique packages. In this case, only biobase (for the shown part) with buttons to each release..?

Anyway, I'm just opening the issue to start the discussion. My point is, this could use of some extra ease for newcomers.

**Comment by DarioS** [comment]
I agree. It's implausible that the user would need to look beyond the first page of results, let alone all eleven thousand of them.

**Comment by mtmorgan** [comment]
The hope was that users would click the first link, which is by design the release version. The ranking is performed by the solr query at https://github.com/Bioconductor/bioconductor.org/blob/master/assets/js/search.js#L18 , so specific improvements there (or in the solr indexing) are welcome. There is a little more information about solr in the top-level README.md and Rakefile.

**Comment by DarioS** [comment]
Oh, it's some Apache server software. The top few search results usually are the relevant ones, so it's probably best left alone. I suppose that limiting the search to the paragraph description of the package and excluding the Depends, Imports, Suggests fields would shorten the results, but doing that with Solr is unknown to me.

Would having "Explore packages" on the homepage in a larger font size than the other links and/or **bold** reduce the reliance on the search box? Locating packages might be the main use of the website, but it doesn't visually stand out from the many other links on there.

**Comment by mtmorgan** [comment]
Including more information from the landing page is generally not helpful, the packages have the same author, title, description etc across versions, and the search engine indexes the site, not just packages, so knows nothing in particular about version. Certainly the 'explore packages' link could be more prominent.

**Comment by Adrianzo** [comment]
I haven't used the search box inside "Explore Packages" before. I'm
comparing the results between one and the other and they even have
different sorting (and matching). IMHO this less-shown search box
should replace the other "solr search box" (which is present on every
page, less friendly and less useful).

**Comment by mtmorgan** [comment]
the 'explore packages' box is really a filter on package author, title, etc in the release, not a search of the other parts of the web site or of packages, e.g., vignettes.

**Comment by Adrianzo** [comment]
Well but you agree that the current main search box isn't useful in searching packages (At least, not as useful as the one in 'explore packages') ?

I'm not asking anyone on the Bioconductor team to change anything. I know you have plenty of work to do! I'm only addressing the difficulty that I believe the website has over newcomers. I'd kindly submit a PR if I had the skills.

Plus, I wonder if the search box is used for anything else but package names. Because I only use it for that. But I understand, maybe that is only me.... 
I guess you log what people search in that box and you know better.

Cheers!
