### ISSUE TITLE
Rank badges link to non-existing pages

### ISSUE THREAD

**Issue by HenrikBengtsson** [Bioconductor/bioconductor.org#209]
For example, the 'rank' badge on <https://www.bioconductor.org/packages/release/bioc/html/Biobase.html> links to <http://bioconductor.org/packages/stats/bioc/Biobase/>, which gives a 403 error;

```sh
 curl --head http://bioconductor.org/packages/stats/bioc/Biobase/
HTTP/1.1 403 Forbidden
Content-Type: text/html
Content-Length: 7136
Connection: keep-alive
Date: Fri, 17 Mar 2023 17:50:05 GMT
Server: Apache/2.4.18 (Ubuntu)
Last-Modified: Fri, 17 Mar 2023 17:35:21 GMT
ETag: "1be0-5f71c0064afd6"
Accept-Ranges: bytes
X-Cache: Error from cloudfront
Via: 1.1 9525a1adf6d0a16da3bb7589fe5684a4.cloudfront.net (CloudFront)
X-Amz-Cf-Pop: SFO5-P1
X-Amz-Cf-Id: MSUo6N8UKdN1deNBfrjBJFKjH13oZcBkGHolqPq9ZMkhuUjhE94xrw==
```

Also, the badge link is an HTTP URL, although it's accessed from an HTTPS address.

**Comment by HenrikBengtsson** [comment]
Actually, all the links on <https://bioconductor.org/packages/stats/> appears to be broken.

**Comment by lshep** [comment]
this 403 error generally occurs when there is an issues with the download stats and actually would normally link to the correct page. We will investigate why the downloads stats are unavailable.
