### ISSUE TITLE
Watched tags overruns character limit

### ISSUE THREAD

**Issue by LTLA** [Bioconductor/bioconductor.org#22]
I need to watch a lot of packages:

```
edger, chipseq, hic, chiapet, csaw, limma, voom, diffhic, scran, scater, interactionset, cydar, beachmat, singlecellexperiment, dropletutils, biocneighbors, simplesinglecell
```

... which leads to the error message:

> Please shorten this text to 100 characters or less (you are currently using 173 characters).

Probably a 10-fold increase in the number of allowable characters would be sufficient.

**Comment by LTLA** [comment]
Oops. Forgot that the support site has its own repo - transferring to Bioconductor/support.bioconductor.org#68.

**Comment by lshep** [comment]
Thanks!  I think we fixed this in the past and might have gotten regressed with the updates.  I'll look into it
