### ISSUE TITLE
https:// pages sometimes redirect to http://

### ISSUE THREAD

**Issue by mtmorgan** [Bioconductor/bioconductor.org#223]
this might be a little vague, but if I am on for instance https://bioconductor.org/packages/BiocParallel and click on one of the badges, e.g., "build", I end up at http://bioconductor.org/checkResults/release/bioc-LATEST/BiocParallel/ but should end up at the equivalent but with `https://`.

This does not seem to happen when I click on other links on the page, e.g., on the links in the 'Documentation' section.

This was mentioned in the community slack https://community-bioc.slack.com/archives/C35G93GJH/p1683122919846559 although I don't know if the original or only cause is clicking on the buttons.

**Comment by ahl27** [comment]
Just to add, it also seems like browsers default to http and not https--at least on iOS and OSX Chrome, going to bioconductor.org navigates to http://bioconductor.org and not https. 

It was mentioned on the slack that the http page has to be kept available for legacy reasons (ex. package installation), but if there's a way to redirect browser access that would be a good feature.

**Comment by lshep** [comment]
Can you test to see if this is resolved?

**Comment by mtmorgan** [comment]
Seems to work as expected now, thanks!
