### ISSUE TITLE
Advertising closed positions

### ISSUE THREAD

**Issue by llrs** [Bioconductor/bioconductor.org#23]
The home page is advertising some positions that are filled (I hope, because they link to a page that says: "We're sorry! The page you are looking for is not available."). 
The relevant lines are here:
 https://github.com/Bioconductor/bioconductor.org/blob/380be1f51a5db80708aba97fd9783b40e62b9d01/content/index.html#L27-L31

**Comment by lshep** [comment]
Thanks! We will look into it.
