### ISSUE TITLE
bad link in citation on landing page

### ISSUE THREAD

**Issue by jwokaty** [Bioconductor/bioconductor.org#245]
I noticed "https://github.com/Mercedeh66/mbQTL" in the citation on https://bioconductor.org/packages/release/bioc/html/mbQTL.html goes to "https://bioconductor.org/packages/release/bioc/html/%22https://github.com/Mercedeh66/mbQTL%22". Maybe because there seems to be some space characters that get interpreted to `%22`?

**Comment by lshep** [comment]
This is generated in biocViews https://code.bioconductor.org/browse/biocViews/blob/devel/R/repository.R#L228  if you run the code https://code.bioconductor.org/browse/biocViews/blob/devel/R/repository.R#L172  It appears this way.  So it seems like its actually an issue in biocViews not bioconductor.org
```
>     citation(pkgname, lib.loc=tmpdir, auto=description)
To cite package 'mbQTL' in publications use:

  Movassagh M, Schiff S, Paulson J (2023). _mbQTL: mbQTL: A package for
  SNP-Taxa mGWAS analysis_. R package version 1.1.0,
  <%22https://github.com/Mercedeh66/mbQTL%22>.

A BibTeX entry for LaTeX users is

  @Manual{,
    title = {mbQTL: mbQTL: A package for SNP-Taxa mGWAS analysis},
    author = {Mercedeh Movassagh and Steven Schiff and Joseph N Paulson},
    year = {2023},
    note = {R package version 1.1.0},
    url = {"https://github.com/Mercedeh66/mbQTL"},
  }

```

**Comment by lshep** [comment]
This citation function is in  `utils::citation` I believe so we might not have control over it
