### ISSUE TITLE
Bad link redirect

### ISSUE THREAD

**Issue by jwokaty** [Bioconductor/bioconductor.org#250]
The link on https://bioconductor.org/packages/devel/workflows/html/annotation.html and on the release version under Details > URL displayed as http://bioconductor.org/help/workflows/annotation/Annotation_Resources/ redirects to https://master.bioconductor.org/packages/release/workflows/html/annotation/Annotation_Resources/index.html, which is not found.

**Comment by lshep** [comment]
This is not an issue with bioconductor.org.  This is an issue with the link provided in the annotation package DESCRIPTION.  I assume it is trying to hit its compiled vignette of the same name or a legacy page that has long since removed or updated.
