### ISSUE TITLE
New website: low res image

### ISSUE THREAD

**Issue by PeteHaitch** [Bioconductor/bioconductor.org#257]
The image above 'Connect With the Community' is a bit jarring when viewed on a bigger screen due to the low resolution / small image
![image](https://github.com/Bioconductor/bioconductor.org/assets/1049741/f80e056a-aa67-4ff9-96c8-d7b5ad4e3858)

**Comment by Sagaaah** [comment]
yes ,it is bit blurred , can i work on this ?

**Comment by lshep** [comment]
we gladly will review any pull requests for any issues
