### ISSUE TITLE
Bioconductor windows binaries for  3.17 not available but yes for 3.16

### ISSUE THREAD

**Issue by zeehio** [Bioconductor/bioconductor.org#263]
Apologies in advance if there's something I'm missing.

The link for the PACKAGES file for Bioconductor 3.16  targeting windows is available at:

https://bioconductor.org/packages/3.16/bioc/bin/windows/contrib/4.2/PACKAGES

I believe the equivalent link for Bioconductor 3.17 should be reachable at:

https://bioconductor.org/packages/3.17/bioc/bin/windows/contrib/4.3/PACKAGES

However, this second link redirects to https://mghp.osn.xsede.org/bir190004-bucket01/archive.bioconductor.org/packages/3.17/bioc/bin/windows/contrib/4.3/PACKAGES and I get as response `NoSuchKeybir190004-bucket01tx0000054e384f476cee9d8-0065c64bc2-626c37-default626c37-default-default`.

When I browse older pages for some Bioconductor package (e.g.: https://www.bioconductor.org/packages/3.16/bioc/html/AlpsNMR.html and https://www.bioconductor.org/packages/3.17/bioc/html/AlpsNMR.html), binary packages for 3.17 are missing and links to those binary packages are broken.

Is that intended behaviour due to a change of policy I have overlooked, or is there an issue somewhere?

Due to this issue, `BiocManager::install(version="3.17")` does not seem to work properly for me on a Windows machine with R-4.3. I get `"cannot open URL https://bioconductor.org/packages/3.17/bioc/bin/windows/contrib/4.3/PACKAGES"` errors.

I don't have a lot of experience on Windows (I usually use Linux) so I may be overlooking something. Any advice is very welcome

Thanks and have a nice weekend :-)

**Comment by almahmoud** [comment]
Hello, thank you for the report and sorry for the issue. There was a bug in the archiving command and the path was wrong (`/bin/` dropped).

It should be fixed now, please verify at your convenience and update us here and/or close the issue if it is resolved.

**Comment by zeehio** [comment]
It is fixed, thank you very much!
