### ISSUE TITLE
Invisible <CONTAINER ID> in 'docker start' and 'docker stop' commands

### ISSUE THREAD

**Issue by hpages** [Bioconductor/bioconductor.org#266]
![image](https://github.com/Bioconductor/bioconductor.org/assets/8810451/89c5a0a7-fda0-4a17-a095-79cd42528a09)

The invisible `<CONTAINER ID>` part gets revealed if one selects the command:

![image](https://github.com/Bioconductor/bioconductor.org/assets/8810451/5e25ec74-1d45-4df6-acfe-ef19ceaa4fce)

![image](https://github.com/Bioconductor/bioconductor.org/assets/8810451/88e2087a-7243-436f-b513-f3421ef09e32)

Thanks,
H.

**Comment by lshep** [comment]
I'm not sure I understand what you mean.  I do not see anything revealed when I select or when I copy/paste?

**Comment by LiNk-NY** [comment]
@lshep 
The `<CONTAINER ID>` in the  `docker start` and `docker stop` commands have a very similar color font as the background. You can see the `<CONTAINER ID>` text if you zoom in or highlight the text with the mouse. 

https://www.bioconductor.org/help/docker/

**Comment by lshep** [comment]
ah got it. thanks

**Comment by hpages** [comment]
Thanks @lshep. I still don't see the `<CONTAINER ID>` part in the `docker start` and `docker stop` commands. Is it because the web site didn't get rebuilt yet?

Note that what is puzzling is that `<CONTAINER ID>` does show up in the `docker exec` and `docker rm` commands.

**Comment by lshep** [comment]
it will take time to propagate. Yes the website will need to be built and pushed.  should appear sometime soon.  Note: you may also have to reset your cache for the changes to appear

**Comment by hpages** [comment]
I see the `<CONTAINER ID>` part now. All is good! Thanks again.
