### ISSUE TITLE
devel package list

### ISSUE THREAD

**Issue by kasperdanielhansen** [Bioconductor/bioconductor.org#295]
When I click on the "Packages" tab at the top of the package, I get taken to the release version of packages. It would be nice if it was easy to switch to the devel view.
![Screenshot 2024-11-07 at 12 38 36](https://github.com/user-attachments/assets/7214cbed-461f-4acb-8230-63b484b5a93d)

I would really like a single button that switches between devel and release, since that is 97% of my usage. I think also having a dropdown that allows switching between release versions would be nice, but would be much less used I think.

**Comment by lshep** [comment]
agreed!  I'll look into this

**Comment by lshep** [comment]
https://github.com/Bioconductor/bioconductor.org/commit/a8c157c1c62b2fe55f94477021f6b94b9f91f58e    I'll wait until the site has a chance to pick up these changes and is officially reflected with no issues before closing.
