### ISSUE TITLE
Install page says Bioc 3.6 works with R 3.4.0

### ISSUE THREAD

**Issue by jdrnevich** [Bioconductor/bioconductor.org#3]
There's something wrong with the auto-generated Bioc and R versions on the install page http://bioconductor.org/install/. It's currently saying:
"The current release of Bioconductor is version 3.6; it works with R version 3.4.0."

Shouldn't this be 3.4.2?

**Comment by LiNk-NY** [comment]
Hi Jenny, @jdrnevich 

The current R versions in our systems can be seen here:

http://bioconductor.org/checkResults/release/bioc-LATEST/
http://bioconductor.org/checkResults/devel/bioc-LATEST/

The initial release used R version `3.4.0`. 
Perhaps it should be changed to `3.4.2`?
@mtmorgan @nturaga 

Regards,
Marcel

**Comment by mtmorgan** [comment]
Sorry to take a while mulling this over; it's a challenging philosophical question! Updated to state the best-practice dependency, which is R-3.4.3.
