### ISSUE TITLE
Text on labels is wider than the image

### ISSUE THREAD

**Issue by llrs** [Bioconductor/bioconductor.org#33]
I noted today that there are some reading problems with the labels on the landing pages:![labels of a package](https://user-images.githubusercontent.com/6818218/64117921-af384600-cd96-11e9-843e-89575de5f9ec.png)

I could see in both Firefox in Ubuntu and in Chrome in Windows. Probably it is related to the badge reorganization in this [commit](d0e2d6085fdb815ee4fd1535250c8997cb9caa22)

**Comment by lshep** [comment]
Thanks. I generated some of the badges in a new way. I'll look into correcting this later this week.

**Comment by lshep** [comment]
Also looking into <6 month broken shield 
https://stat.ethz.ch/pipermail/bioc-devel/2019-September/015583.html

**Comment by lshep** [comment]
haven't forgotten about this -  just been tied up with a few other things -  plan to get to it tomorrow or early next week

**Comment by lshep** [comment]
Should be corrected now.  Sorry for the delay

**Comment by llrs** [comment]
Many thanks, now it looks great again!

**Comment by lshep** [comment]
Sorry it took so long
