### ISSUE TITLE
package short URL without https

### ISSUE THREAD

**Issue by sneumann** [Bioconductor/bioconductor.org#34]
Hi, the URL to the package short link is http-only:
Package Short Url | http://bioconductor.org/packages/xcms/
Yours, Steffen

**Comment by mtmorgan** [comment]
I'm not sure that I understand -- http://bioconductor.org/packages/xcms redirects to http://..., and https://bioconductor.org/packages/xcms redirects to https://... ?

**Comment by sneumann** [comment]
Hi, my main point was that nowadays URLs should point to https instead of http,
hence the PR (where I guessed) the `Package Short Url` shown on the package pages 
is created, so that it'll be `Package Short Url: httpS://bioconductor.org/packages/xcms/`

I don't fully know how the http redirects are created behind the scenes,
indeed it redirects http://bioconductor.org/packages/xcms to http://bioconductor.org/.../xcms.html, 
but in contrast to what you said, 
https://bioconductor.org/packages/xcms/ is forwarded to non-https:
http://bioconductor.org/.../xcms.html  which might be a separate thing to look into, next time when someone touches the redirect mechanism. 

So nothing fundamentally broken at the moment, but the https migration is not complete yet ;-)
Yours, Steffen
