### ISSUE TITLE
SSL peer certificate or SSH key is not OK

### ISSUE THREAD

**Issue by llrs** [Bioconductor/bioconductor.org#36]
Got a warning about 

URL 'https://bioconductor.org/config.yaml': status was 'SSL peer certificate or SSH remote key was not OK'

If I go to the url I see:

![Screenshot from 2019-10-03 22-48-10](https://user-images.githubusercontent.com/6818218/66163163-f92f7880-e62f-11e9-8156-d5bb3404dbdb.png)

In addition, I see this :

```r
> BiocManager::valid()
Warning: unable to access index for repository https://bioconductor.org/packages/3.9/bioc/src/contrib:
  cannot open URL 'https://bioconductor.org/packages/3.9/bioc/src/contrib/PACKAGES'
Warning: unable to access index for repository https://bioconductor.org/packages/3.9/data/annotation/src/contrib:
  cannot open URL 'https://bioconductor.org/packages/3.9/data/annotation/src/contrib/PACKAGES'
Warning: unable to access index for repository https://bioconductor.org/packages/3.9/data/experiment/src/contrib:
  cannot open URL 'https://bioconductor.org/packages/3.9/data/experiment/src/contrib/PACKAGES'
Warning: unable to access index for repository https://bioconductor.org/packages/3.9/workflows/src/contrib:
  cannot open URL 'https://bioconductor.org/packages/3.9/workflows/src/contrib/PACKAGES'
```

**Comment by mtmorgan** [comment]
yes this has been reported on the bioc-devel mailing list and support site; the certificate is being updated for instance https://master.bioconductor.org should be valid again. The update needs to propagate (it has not yet) through cloud front to https://bioconductor.org and your browser cache may need to be flushed.

**Comment by llrs** [comment]
Great, I didn't saw the message on the mailing list, sorry
