### ISSUE TITLE
HTTP -> HTTPS

### ISSUE THREAD

**Issue by HenrikBengtsson** [Bioconductor/bioconductor.org#37]
FYI, https://www.bioconductor.org/news/bioc_3_10_release/ links to http://bioconductor.org/install/ (using HTTP).  Maybe there are other HTTP links.

Also, would it make sense to redirect all HTTP requests to HTTPS in the webserver?  Right now, if you go to http://bioconductor.org/ you'll remain in HTTP space when browsing around.

**Comment by mtmorgan** [comment]
actually, some people do not have https access...

**Comment by HenrikBengtsson** [comment]
oh... I thought it was only the other way around.  I'm curious, what causes some to not have HTTPS access?

**Comment by mtmorgan** [comment]
Restrictive access policies? I really don't know but it comes up periodically; it's as surprising to me as blocked ssh.

**Comment by HenrikBengtsson** [comment]
Righty'oh. I'm amazed that they can even get things done (also in R and Bioconductor) these days with HTTP-only.

**Comment by hpages** [comment]
still: the release announcement first links to https://bioconductor.org, then to  http://bioconductor.org/install/

!?

**Comment by LiNk-NY** [comment]
The second link should use `https`, no?
https://bioconductor.org/news/bioc_3_10_release/
