### ISSUE TITLE
Forwarding users from simpleSingleCell?

### ISSUE THREAD

**Issue by LTLA** [Bioconductor/bioconductor.org#5]
Currently, if people look for:

https://www.bioconductor.org/help/workflows/simpleSingleCell/

... they get the old version of the workflow. It is possible to forward people onto:

https://www.bioconductor.org/help/workflows/simpleSingleCell/intro

... which acts as an indexing page for the new version of the workflow?

**Comment by LTLA** [comment]
Bumping this issue - any thoughts?

**Comment by vobencha** [comment]
Hi Aaron,
There is no link (I know of) on the website that points to 

  https://www.bioconductor.org/help/workflows/simpleSingleCell/

For a user to get there they would have to manually type it in. Unless I've missed one ... ?

Regardless, I've added a redirect that sends people to 

https://www.bioconductor.org/help/workflows/simpleSingleCell/intro

Valerie

**Comment by LTLA** [comment]
The link is present in the original F1000Research paper - it's possible to change it, but then I would have to submit a new revision, etc. which would be a real pain. It's also probably present in a variety of support site posts that I'm not sure how to get to because of the eccentricities of the search engine.

But anyway, thanks for doing this - I hope it wasn't too much effort on your part.

**Comment by vobencha** [comment]
Unfortunately the quick fix didn't work. The generation of these index files is somewhat complicated - we're working on it and will let you know when we have a permanent solution in place.

**Comment by LTLA** [comment]
Thanks Val. That's funny, I thought it was working when I checked it out last night. Will wait for the fix.

**Comment by LTLA** [comment]
This seems to have been fixed (https://support.bioconductor.org/p/108421/#108444), so closing.
