### ISSUE TITLE
Error in Biostrings

### ISSUE THREAD

**Issue by heleendelbeke** [Bioconductor/bioconductor.org#52]
Hi all,

Even in these horrific times of COVID-19 pandemic we try to focus on our research.

The DADA2 pipeline Tutorial was very useful but now I am struggling big time on the phyloseq part.
I just removed all Eukaryota en NA from my data set: 
ps_EPSO1_noEuks_noUnk <- subset_taxa(ps_EPSO1, Kingdom!="Eukaryota" &
                                             Phylum!=" ")

> print(ps_EPSO1_noEuks_noUnk)
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 3455 taxa and 40 samples ]
sample_data() Sample Data:       [ 40 samples by 13 sample variables ]
tax_table()   Taxonomy Table:    [ 3455 taxa by 6 taxonomic ranks ]
refseq()      DNAStringSet:      [ 3455 reference sequences ]

But I receive on my next step an error:

> dna <- Biostrings::DNAStringSet(taxa_names(ps_EPSO1_noEuks_noUnk))
**Error in .Call2("new_XStringSet_from_CHARACTER", class(x0), elementType(x0),  : 
  key 51 (char '3') not in lookup table**

If I look at my ps_EPSO1_noEuks_noUnk, my pay_tree is NULL. I have no idea how come.

Some help would be much appreciated!

BW
H.

**Comment by lshep** [comment]
This is not an issue with the Bioconductor website which is what this repo is for.  Could you please repost this is the Biostrings github repository.  https://github.com/Bioconductor/Biostrings
