### ISSUE TITLE
bioclite

### ISSUE THREAD

**Issue by sengoku93** [Bioconductor/bioconductor.org#7]
Hi,

Do you have to reinstall bioclite every single time you open rstudio? I ask this because that is what is happening to me. Is there a way to install bioclite permanently? Thank you!

**Comment by mtmorgan** [comment]
Please ask questions on the Bioconductor support site https://support.bioconductor.org .

```
source("https://bioconductor.org/biocLite.R")
```
installs the package BiocInstaller, and one can then `BiocInstaller::biocLite()`.
