### ISSUE TITLE
Preview of the support site from main project site

### ISSUE THREAD

**Issue by federicomarini** [Bioconductor/bioconductor.org#74]
Hi, 
I'd have a quick feedback on the new support site (which looks so much better, well done!) - when checking from the Bioc homepage, the post type information generate “extra clutter”

![image](https://user-images.githubusercontent.com/7447478/97006699-86e24c80-1540-11eb-91b5-d1c28d0740a2.png)

i.e. I probably would not need to see Comment: Comment: or Answer: Answer: , but rather “the most” of each post title.
Is this unexpected or desired to be this way? Just thinking out loud, as maybe some changes are unwanted side effects after switching.

As @lshep pointed out in Slack, 

> this actually is more to do with how the main site gets the recent posts but will have to look further into it

This is mainly to make the original conversation less volatile 😃 
Thanks for looking into it!
Federico

**Comment by lshep** [comment]
This has been resolved with the update of the RSS feed for support.bioconductor.org .   cheers
