### ISSUE TITLE
WISH: Make it clear that Bioc 3.12 requires R (>= 4.0.0)

### ISSUE THREAD

**Issue by HenrikBengtsson** [Bioconductor/bioconductor.org#76]
I find the R version requirement on https://bioconductor.org/install/:

> The current release of Bioconductor is version 3.12; it works with R version 4.0.3. Users of older R and Bioconductor must update their installation ...

ambiguous, i.e. I read it as R (>= 4.0.3) was required.  Per https://github.com/Bioconductor/BiocManager/issues/82#issuecomment-723483039, R 4.0.0 should be sufficient.  May I suggest to update the webpage to read:

The current release of Bioconductor is version 3.12; it requires R version 4.0.0 or newer where R version 4.0.3 is highly recommended. Users of older R and Bioconductor must update their installation ...

I see that "4.0.3" comes from `r_version_associated_with_release` in:

https://github.com/Bioconductor/bioconductor.org/blob/f840e3f1a904f189d057c5deda1d4b9d94a4e303/config.yaml#L11

**Comment by mtmorgan** [comment]
This is a statement about the version of R used on the build system to produce the release packages. We actually have no way of knowing (in general) whether packages would 'work' if built with R 4.0.0, and certainly not of knowing the future implied by  a `>` version specification.

I will close the issue, without making changes.
