### ISSUE TITLE
Question badge link should be updated

### ISSUE THREAD

**Issue by llrs** [Bioconductor/bioconductor.org#94]
The badges linking to a tag on support.bioconductor.org should update their scheme since the update of the support site.
From: `https://support.bioconductor.org/t/omixer/` to `https://support.bioconductor.org/tag/omixer/`.
The first one is valid but returns a mixed set of questions while the new one is just for said tag. 

Not sure where the template it otherwise I would directly sent a PR.

**Comment by lshep** [comment]
thanks!  there was a recent rollout yesterday or the day before that made this change.  I'll work on the update later this morning.

**Comment by lshep** [comment]
Updated in  https://github.com/Bioconductor/bioconductor.org/commit/42393db2e4551c7e4feda452d915ead072309023

**Comment by llrs** [comment]
Great, so fast! Thanks Lori
